### ISSUE TITLE
一片黑屏怎么回事，求解

### ISSUE THREAD

**Issue by fuyuer233** [Kaiser-DMr/-3D#1]
一片黑屏怎么回事，求解

**Comment by hmy02** [comment]
同问

**Comment by Kaiser-DMr** [comment]
看readme有说明github直接下载需要在index.HTML中修改引入js文件的路径

**Comment by Kaiser-DMr** [comment]
> 一片黑屏怎么回事，求解

github直接下载需要在index.HTML中修改引入js文件的路径

**Comment by fuyuer233** [comment]
> 看readme有说明github直接下载需要在index.HTML中修改引入js文件的路径

我知道了，好像得等一会才有 @hmy02
